import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import Header from './components/layout/Header'
import Footer from './components/layout/Footer'

const openSans = Open_Sans({
  subsets: ['latin', 'cyrillic'], // Поддерживаемые языки
  weight: ['400', '600', '700'], // Начертания
  variable: '--font-open-sans', // CSS-переменная (опционально)
})

export const metadata: Metadata = {
  title: 'QWERy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased bg-black text-white`}>
        <div className="min-h-screen flex flex-col">
          {/* Фоновое изображение с градиентом */}
          <div className="absolute inset-0 -z-10">
            <div
              className="absolute inset-0 bg-[url('/images/Background.png')] bg-cover bg-center"
              style={{
                maskImage:
                  'linear-gradient(to bottom, black 0%, black 70%, transparent 100%)',
                WebkitMaskImage:
                  'linear-gradient(to bottom, black 0%, black 70%, transparent 100%)',
              }}
            />
          </div>
          <Header />
          <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 p-22">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
